---
service_map:
  zk:
    - apigee-zookeeper
  c:
    - apigee-cassandra
  ds:
    - apigee-cassandra
    - apigee-zookeeper
  ld:
    - apigee-openldap
  ms:
    - apigee-openldap
    - edge-management-server
    - edge-ui    
  r:
    - edge-router
  mp:
    - edge-message-processor
  rmp:
    - edge-router
    - edge-message-processor
  qs:
    - apigee-qpidd
    - edge-qpid-server
  ps:
    - apigee-postgresql
    - edge-postgres-server
  sax:
    - apigee-qpidd
    - edge-qpid-server
    - apigee-postgresql
    - edge-postgres-server