---
- name: Setup {{ profile }}
  become: yes
  command: bash /opt/apigee/apigee-setup/bin/setup.sh -p {{ profile }} -f /tmp/apigee/response_{{ planet }}_{{ hostvars[inventory_hostname]['region'] }}.cfg
  async: 3600
  poll: 5
  when: cmd == "setup"

- name: Running apigee-service
  become: yes
  command: /opt/apigee/apigee-service/bin/apigee-service {{ item }} {{ cmd }}
  register: status
  async: 3600
  poll: 5
  when: cmd != "setup"
  with_items: 
    - "{{ service_map[profile] }}"

- debug: msg="{{ item.stdout_lines }}"
  when: cmd != "setup"
  with_items:
    - "{{ status.results }}"
