---
# tasks file for port-connectivity-validator
- name: Cassandra client port connectivity status  
  shell: |
    PASS=`nmap {{ hostvars[item.0].ansible_host }} -p {{  cassandra_ports[item.1] }}|awk -F'/' '/filtered/ {print $1}'`;
    if [ ${PASS} -eq {{ cassandra_ports[item.1] }} ]; then 
      RESULT="false"
    else
      RESULT="true"
    fi
    echo "{{ ansible_host }},$RESULT,{{ hostvars[item.0].ansible_host }},{{ item.0 }},{{ cassandra_ports[item.1] }},{{ item.1 }}" 
  register: 'cassandra_port_status'
  ignore_errors: yes
  with_nested:
    - '{{ groups["cs"] | difference([inventory_hostname]) }}'
    - '{{ cassandra_ports }}'

- name: Set Fact Thrift port
  set_fact:  
    cassandra_port: '{{ cassandra_port_status.results }}'