---  
# Region condition
- name: Set region flag
  set_fact:
    node_region: "{{ hostvars[inventory_hostname]['region'] }}"

- include: zk.yml
  when: inventory_hostname in groups['ds']

- include: cs.yml
  when: inventory_hostname in groups['ds']

- include: ms.yml
  when: inventory_hostname in groups['ms']

- include: mp.yml
  when: inventory_hostname in groups['mp']

- include: r.yml
  when: inventory_hostname in groups['r']